# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-home-task-SS"
client_id = "8a561d6b520e82170b801c4d8d1d45bb"
application_url = "https://bras-establish-firewall-departments.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://bras-establish-firewall-departments.trycloudflare.com/auth/callback",
  "https://bras-establish-firewall-departments.trycloudflare.com/auth/shopify/callback",
  "https://bras-establish-firewall-departments.trycloudflare.com/api/auth/callback",
  "https://bras-establish-firewall-departments.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-37.myshopify.com"
